"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var AHH = {
    WORKS: {
        ko: {
            langs: [
                {
                    key: 1,
                    desc: [
                        "Meta exam",
                        "",
                        "React.js, Sass기반으로 특정 추가 페이지만 디자인 \n, 유지보수 및 ui 퍼블리싱 100%",
                        "영어 시험 웹앱. React 기반으로 개발하였으며, 학원 특성상 태블릿을 주로 사용하므로 태블릿에 맞춘 반응형 레이아웃 유지보수에 중점적으로 참여. ",
                        "https://rosaceaee.github.io/static/media/meta3.904951598c3fff97aade.jpg",
                    ],
                    link: "https://culp.cloubot.com/login",
                    bg: "https://rosaceaee.github.io/static/media/meta3.904951598c3fff97aade.jpg",
                },
                {
                    desc: [
                        "Phonics monster",
                        "",
                        "유지보수 및 ui 퍼블리싱 100%(태블릿, 모바일)",
                        "영어 교육용 웹앱. \n 프로젝트 투입 전에 이미 뼈대는 작업 되어있었으나 미완성된 레이아웃으로 데스크탑부터 태블릿, 모바일까지 모두 반응형 작업 진행.",
                        "https://rosaceaee.github.io/static/media/pn1.e00496c64cf59b356fd6.png",
                    ],
                    link: "https://epublic-phonics.cloubot.com/",
                    go: [""],
                    bg: "https://rosaceaee.github.io/static/media/pn1.e00496c64cf59b356fd6.png",
                },
                {
                    desc: [
                        "LMS",
                        "",
                        "Learning Manage System 페이지. 영어학원의 강사용, 학생용 관리자 웹,앱.",
                        "React.js, Sass기반으로 ui 퍼블리싱 80%(데스크톱, 태블릿, 모바일), 유지보수 작업",
                        "",
                    ],
                    link: "https://culp.cloubot.com/login",
                    go: [""],
                    bg: "",
                },
                {
                    desc: [
                        "루시드 영어학원",
                        "",
                        "영어 교육용 앱. \n React.js, React-native, Sass로 개발. 웹앱과 앱 모두 작업",
                        "디자인: 레이아웃, 색상 선정 참여 나머지 부분은 외주 디자이너의 시안대로 진행, \n ui 퍼블리싱 100%(데스크톱, 태블릿, 모바일)",
                        "https://rosaceaee.github.io/static/media/lucid1.fe2744fd89cc3e97aed3.jpeg",
                    ],
                    link: "https://play.google.com/store/apps/details?id=com.culpmobile.lucid",
                    go: [""],
                    bg: "https://rosaceaee.github.io/static/media/lucid1.fe2744fd89cc3e97aed3.jpeg",
                },
                {
                    desc: [
                        "크레오 영어학원 교육용 앱",
                        "",
                        "리액트 네이티브 기반으로 모든 페이지 퍼블리싱 100% 진행",
                        "Sass, React, React-native로 작업(웹앱, 안드로이드 앱 작업)",
                        "https://rosaceaee.github.io/static/media/creo.93394473494f6ef607ce.png",
                    ],
                    link: "https://play.google.com/store/apps/details?id=com.culpmobile.creo",
                    go: [""],
                    bg: "https://rosaceaee.github.io/static/media/creo.93394473494f6ef607ce.png",
                },
                {
                    desc: [
                        "개인 페이지: 인터렉티브 디자인 구현",
                        "",
                        "주로 랜딩 페이지에서 사용되는 애니메이션 효과 적용",
                        "",
                        "https://rosaceaee.github.io/static/media/meta3.904951598c3fff97aade.jpg",
                    ],
                    link: "https://rosaceaee.github.io/sample-for-port/",
                    bg: "https://rosaceaee.github.io/static/media/meta3.904951598c3fff97aade.jpg",
                },
                {
                    desc: [
                        "개인 페이지: 간단한 영단어 기록단어장",
                        "",
                        "주로 랜딩 페이지에서 사용되는 애니메이션 효과 적용",
                        "",
                        "https://rosaceaee.github.io/static/media/meta3.904951598c3fff97aade.jpg",
                    ],
                    link: "https://rosaceaee.github.io/studyLang_en/",
                    bg: "https://rosaceaee.github.io/static/media/meta3.904951598c3fff97aade.jpg",
                },
                {
                    desc: [
                        "파란관세사무소",
                        "https://www.weibo.com",
                        "퍼블리싱 100%(데스크톱, 태블릿, 모바일)",
                        "자잘한 오류가 상당히 많아 유지보수 작업. 포털 사이트 리뉴얼과 고객사 전용 빌더 레이아웃, 기능(서버 디비에서 페이지로 ajax를 이용해 불러오는 등) 작업을 수행.            ",
                        "https://corydalis.github.io/pt/img/blue1.png",
                    ],
                    link: "http://bluecustoms.co.kr/",
                    go: [""],
                    bg: "https://corydalis.github.io/pt/img/blue1.png",
                },
                {
                    desc: [
                        "스펙토리",
                        "https://www.weibo.com",
                        "메인 플랫폼 사이트의 유지보수 작업",
                        "jsp, jQuery로 유지보수",
                        "https://corydalis.github.io/pt/img/blue1.png",
                    ],
                    link: "https://www.spectory.net/",
                    go: [""],
                    bg: "https://corydalis.github.io/pt/img/spec1.png",
                },
                {
                    desc: [
                        "서울여대 아동학과",
                        "https://www.weibo.com",
                        "추가 요청으로 메인페이지, 학과소개 페이지 유지보수 참여",
                        "jQuery로 유지보수",
                        "https://corydalis.github.io/pt/img/blue1.png",
                    ],
                    link: "https://childstudy.swu.ac.kr/",
                    go: [""],
                    bg: "https://corydalis.github.io/pt/img/sw1.png",
                },
                {
                    desc: [
                        "해양수산창업콘테스트",
                        "",
                        "유지보수 참여",
                        "jQuery로 유지보수",
                        "",
                    ],
                    link: "http://www.seastartup.kr/home/start.php",
                    go: [""],
                    bg: "https://rosaceaee.github.io/static/media/sea.1d75ab5657470f136abb.png",
                },
                {
                    desc: [
                        "SSmedipia",
                        "https://www.weibo.com",
                        "디자인: 메인페이지, 서브페이지 레이아웃 참여, 퍼블리싱 및 유지보수 참여 100%",
                        "jQuery로 유지보수",
                        "https://corydalis.github.io/pt/img/ss1.png",
                    ],
                    link: "http://www.ssmedipia.com/",
                    go: ["ddddd"],
                    bg: "https://corydalis.github.io/pt/img/ss1.png",
                },
                {
                    desc: [
                        "공간산업 주식회사",
                        "",
                        "디자인: 메인페이지, 서브페이지 레이아웃 참여, 퍼블리싱 및 유지보수 참여 100%",
                    ],
                    link: "http://www.spcdoor.com/",
                    go: [""],
                    bg: "https://corydalis.github.io/pt/img/sp1.png",
                },
            ],
        },
        en: {
            langs: [
                {
                    desc: [
                        "Meta exam",
                        "",
                        "Designed few pages, developed all the UI pages(including responsive work), maintenance of UI structure",
                        "Site for English exam in English school teachers built only React.js.",
                        "https://rosaceaee.github.io/static/media/meta3.904951598c3fff97aade.jpg",
                    ],
                    link: "https://culp.cloubot.com/login",
                    bg: "https://rosaceaee.github.io/static/media/meta3.904951598c3fff97aade.jpg",
                },
                {
                    desc: [
                        "Phonics monster",
                        "",
                        "maintenance of UI structure, responsive design",
                        "Web and Mobile App for English learning. Participated in maintanance of UI(responsive)",
                        "https://rosaceaee.github.io/static/media/pn1.e00496c64cf59b356fd6.png",
                    ],
                    link: "https://epublic-phonics.cloubot.com/",
                    go: [""],
                    bg: "https://rosaceaee.github.io/static/media/pn1.e00496c64cf59b356fd6.png",
                },
                {
                    desc: [
                        "LMS",
                        "",
                        "App for learning English Creo English school(Learning Manage System page).",
                        "Developed React-Native.js, maintained the UI to all the pages",
                    ],
                    link: "https://culp.cloubot.com/login",
                    go: [""],
                    bg: "https://rosaceaee.github.io/static/media/creo.93394473494f6ef607ce.png",
                },
                {
                    desc: [
                        "Lucid English",
                        "",
                        "Participated in Responsive and layout design, UI structure(desktop, tablet, mobile)",
                        "Developed in React.js, React-native, Sass. (Web app and Android app)",
                        "https://corydalis.github.io/pt/img/blue1.png",
                    ],
                    link: "https://play.google.com/store/apps/details?id=com.culpmobile.lucid",
                    go: [""],
                    bg: "https://rosaceaee.github.io/static/media/lucid1.fe2744fd89cc3e97aed3.jpeg",
                },
                {
                    desc: [
                        "English learning app for Creo english school",
                        "",
                        "English learning tool for Creo english school",
                        "Developed the UI to all the pages with Sass, React, React-Native. (Web app and Android app)",
                        "https://rosaceaee.github.io/static/media/creo.93394473494f6ef607ce.png",
                    ],
                    link: "https://play.google.com/store/apps/details?id=com.culpmobile.creo",
                    go: [""],
                    bg: "https://rosaceaee.github.io/static/media/creo.93394473494f6ef607ce.png",
                },
                {
                    desc: [
                        "Paran customs office",
                        "",
                        "customs office in korea. Participated in responsive and layout design(desktop, tablet, mobile)",
                        "Developed using JQuery, Css3, Bootstrap",
                        "https://corydalis.github.io/pt/img/blue1.png",
                    ],
                    link: "http://bluecustoms.co.kr/",
                    go: [""],
                    bg: "https://corydalis.github.io/pt/img/blue1.png",
                },
                {
                    desc: [
                        "Spectory",
                        "",
                        "Platform site for compParticipated in layout design, and UI structure(desktop, tablet, mobile)",
                        "Developed using Jsp, jQuery",
                        "",
                    ],
                    link: "https://www.spectory.net/",
                    go: [""],
                    bg: "https://corydalis.github.io/pt/img/spec1.png",
                },
                {
                    desc: [
                        "Childstudy Dept. of Seoul women's university ",
                        "",
                        "Participated in UI maintenance of main page, some of detail pages",
                        "Developed using JQuery, Css3, Bootstrap",
                        "https://corydalis.github.io/pt/img/blue1.png",
                    ],
                    link: "https://childstudy.swu.ac.kr/",
                    go: [""],
                    bg: "https://corydalis.github.io/pt/img/sw1.png",
                },
                {
                    desc: [
                        "Contest of startup in Ministry of Oceans and Fisheries",
                        "",
                        "Site for national contest. Participated in UI maintenance",
                        "Developed using JQuery, Css3",
                        "https://corydalis.github.io/pt/img/blue1.png",
                    ],
                    link: "http://www.seastartup.kr/home/start.php",
                    go: [""],
                    bg: "https://rosaceaee.github.io/static/media/sea.1d75ab5657470f136abb.png",
                },
                {
                    desc: [
                        "SSmedipia",
                        "",
                        "The company about blood clotting diagnostic equipment. Participated in responsive and layout design, UI structure(desktop, tablet, mobile)",
                        "Developed using JQuery, Css3, Bootstrap",
                        "https://corydalis.github.io/pt/img/ss1.png",
                    ],
                    link: "http://www.ssmedipia.com/",
                    go: [""],
                    bg: "https://corydalis.github.io/pt/img/ss1.png",
                },
                {
                    desc: [
                        "Gonggan instructure Inc.",
                        "",
                        "The company to supply doors for various industry. Participated in layout design, and UI structure(desktop, tablet, mobile)",
                        "Developed using JQuery, Css3, Bootstrap",
                    ],
                    link: "http://www.spcdoor.com/",
                    go: [""],
                    bg: "https://corydalis.github.io/pt/img/sp1.png",
                },
            ],
        },
        ja: {
            langs: [
                {
                    desc: [
                        "Meta exam",
                        "",
                        "(内部方針で外部からアクセスが不可ですのでご了承ください) アプリ接続のページのみデザイン及びUI開発、メンテナンス,",
                        "英語塾で行う英語試験サイトの制作、REACT・SASSでUI開発",
                        "https://rosaceaee.github.io/static/media/meta3.904951598c3fff97aade.jpg",
                    ],
                    link: "",
                    bg: "https://rosaceaee.github.io/static/media/meta3.904951598c3fff97aade.jpg",
                },
                {
                    desc: [
                        "Phonics monster",
                        "",
                        "(内部方針で外部からアクセスが不可ですのでご了承ください) UIメンテナンスの作業",
                        "英語発音教育のアプリ。REACT・SASSでUI作業。主に全てのレスポンシブ100%作業",
                        "https://rosaceaee.github.io/static/media/pn1.e00496c64cf59b356fd6.png",
                    ],
                    link: "https://epublic-phonics.cloubot.com/",
                    go: [""],
                    bg: "https://rosaceaee.github.io/static/media/pn1.e00496c64cf59b356fd6.png",
                },
                {
                    desc: [
                        "LMS",
                        "",
                        "(内部方針で外部からアクセスが不可ですのでご了承ください) 英語塾の教師・学生向け管理者ページ(Learning manage system)",
                        "React・SASSでUI開発及びメンテナンス",
                        "https://rosaceaee.github.io/static/media/1.6ab6e2c6b7b236116320.png",
                    ],
                    link: "https://culp.cloubot.com/login",
                    go: [""],
                    bg: "https://rosaceaee.github.io/static/media/1.6ab6e2c6b7b236116320.png",
                },
                {
                    desc: [
                        "ルシド英語スクール",
                        "",
                        "REACT・SASSを基づいてレイアウトデザイン、レスポンシブデザイン及びUI開発の作業。",
                        "英語教育のアプリ、REACTで開発",
                        "https://rosaceaee.github.io/static/media/lucid1.fe2744fd89cc3e97aed3.jpeg",
                    ],
                    link: "https://play.google.com/store/apps/details?id=com.culpmobile.lucid",
                    go: [""],
                    bg: "https://rosaceaee.github.io/static/media/lucid1.fe2744fd89cc3e97aed3.jpeg",
                },
                {
                    desc: [
                        "English learning app for Creo english",
                        "",
                        "Creo英語スクールの英語教育用アプリ。Learning Manage System（管理者ページ）。React-Nativeで全てのページのUI開発",
                        "",
                        "https://rosaceaee.github.io/static/media/creo.93394473494f6ef607ce.png",
                    ],
                    link: "https://play.google.com/store/apps/details?id=com.culpmobile.creo",
                    go: [""],
                    bg: "https://rosaceaee.github.io/static/media/creo.93394473494f6ef607ce.png",
                },
                {
                    desc: [
                        "パラン関税事務所",
                        "",
                        "関税事務所のサイト。パランは韓国語で「青」の意味で、カラーも同じく青色で選択。メインカラーデザイン・レイアウトデザイン及びUI開発の作業。",
                        "CSS3・Bootstrap・JQueryで開発",
                        "https://corydalis.github.io/pt/img/blue1.png",
                    ],
                    link: "http://bluecustoms.co.kr/",
                    go: [""],
                    bg: "https://corydalis.github.io/pt/img/blue1.png",
                },
                {
                    desc: [
                        "スペックトリ",
                        "",
                        "コンペのまとめサイト。他に提供してるホームページビルダーのサービスもメンテナンスも担当。UIメンテナンス、レスポンシブデザイン作業",
                        "Jsp, JQueryで開発",
                        "https://corydalis.github.io/pt/img/blue1.png",
                    ],
                    link: "https://www.spectory.net/",
                    go: [""],
                    bg: "https://corydalis.github.io/pt/img/spec1.png",
                },
                {
                    desc: [
                        "ソウル女子大学校 児童学科",
                        "",
                        "主にメンテナンス担当。メイン、学科紹介ページのUIメンテナンス作業",
                        "CSS3・Bootstrap・JQueryで開発",
                        "https://corydalis.github.io/pt/img/blue1.png",
                    ],
                    link: "https://childstudy.swu.ac.kr/",
                    go: [""],
                    bg: "https://corydalis.github.io/pt/img/sw1.png",
                },
                {
                    desc: [
                        "海洋水産部のコンペ",
                        "",
                        "サイトのリニューアル・UIメンテナンス作業",
                        "JQueryで開発",
                        "https://corydalis.github.io/pt/img/blue1.png",
                    ],
                    link: "http://www.seastartup.kr/home/start.php",
                    go: [""],
                    bg: "https://rosaceaee.github.io/static/media/sea.1d75ab5657470f136abb.png",
                },
                {
                    desc: [
                        "SSmedipia",
                        "",
                        "血液に関する企業で、レスポンシブ・レイアウトデザイン及びUIメンテナンスで作業",
                        "CSS3・Bootstrap・JQueryで開発",
                        "https://corydalis.github.io/pt/img/ss1.png",
                    ],
                    link: "http://www.ssmedipia.com/",
                    go: [""],
                    bg: "https://corydalis.github.io/pt/img/ss1.png",
                },
                {
                    desc: [
                        "コンガン産業株式会社",
                        "",
                        "産業用ドア制作企業、レイアウトデザイン及びUIメンテナンスで作業",
                        "CSS3・Bootstrap・JQueryで開発",
                    ],
                    link: "https://www.googlre.com",
                    go: [""],
                    bg: "https://corydalis.github.io/pt/img/sp1.png",
                },
            ],
        },
    },
    ABOUT: {
        ko: {
            langs: [
                {
                    key: 1,
                    desc: [
                        "장영주",
                        "웹 퍼블리셔",
                        "원만한",
                        "끈기있는",
                        "차분한",
                        "고여있는 것보다 접해보지 못한 다양한 경험을 하는 것을 좋아합니다. ",
                        "IT업계에서 근무하는 동안 UI디자인과 프론트엔드 개발에 관심이 많아 디자인과 개발 사이에서 유연하게 대응할 수 있습니다.",
                        "쉬는 날에는 주로 닌텐도 스위치게임을, 조깅 혹은 자전거 라이딩을, 친구들과 산책을 하며 재충전의 시간을 가지고 있습니다! 물론 mdn 문서를 보며 개발공부도 꾸준히 하고있습니다. ",
                    ],
                },
            ],
        },
        en: {
            langs: [
                {
                    key: 2,
                    desc: [
                        "young joo Jang",
                        "UI developer",
                        "flexible",
                        "patient",
                        "calm",
                        "Likes having various experience that haven't experienced before using new ways.",
                        "I'm interested in UI design, frontend development, and can handle flexibly between it.",
                        "And in out of the computer, I usually play a nintendo switch games(Zelda series), jogging and riding bycircle, hangout with my friends. Of course, Studying a development and design also!",
                    ],
                },
            ],
        },
        ja: {
            langs: [
                {
                    key: 3,
                    desc: [
                        "young joo Jang",
                        "マークアップエンジニア・コーダー",
                        "円満な",
                        "根気強い",
                        "落ち着いた",
                        "接したことがなかった多様な経験をすることが好きです。",
                        "UIデザインとフロントエンド開発に興味深くて、今までマークアップ開発とフロントエンド開発の間で働いた経験を基づいて両方対応することができます。",
                        "休みにはNintendo Switchゲーム（ゼルダシリーズ）をプレイしたり、ジョギングや自転車でらいでぃんぐをしたり、友達とお出かけをして楽しく休みます！もちろん、開発とデザインの勉強も！",
                    ],
                },
            ],
        },
    },
};
exports.default = AHH;
