"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var AHH = {
    WORKS: {
        ko: {
            langs: [
                {
                    key: 0,
                    desc: [
                        "영어단어장",
                        "",
                        "개인 토이프로젝트, 예상 주요타겟은 기초 영단어를 공부하는 중노년층이며 계속 추가 기능 개발진행중, 모바일 화면에서만 확인 가능.",
                        "React, SASS",
                        "",
                    ],
                    link: "https://rosaceaee.github.io/studyLang_en/",
                    bg: "",
                },
                {
                    key: 1,
                    desc: [
                        "Meta exam",
                        "",
                        "React, Sass기반으로 특정 추가 페이지만 디자인 \n, 유지보수 및 ui 퍼블리싱 100%",
                        "영어 시험 웹앱. React 기반으로 개발하였으며, 학원 특성상 태블릿을 주로 사용하므로 태블릿에 맞춘 반응형 레이아웃 유지보수에 중점적으로 참여. ",
                        "",
                    ],
                    link: "https://metaexam-lexile.com/meta-login",
                    bg: "",
                },
                {
                    desc: [
                        "Phonics monster",
                        "",
                        "유지보수 및 ui 퍼블리싱 100%(태블릿, 모바일)",
                        "영어 교육용 웹앱. \n 프로젝트 투입 전에 이미 뼈대는 작업 되어있었으나 미완성된 레이아웃으로 데스크탑부터 태블릿, 모바일까지 모두 반응형 작업 진행.",
                        "https://rosaceaee.github.io/static/media/pn1.e00496c64cf59b356fd6.png",
                    ],
                    link: "https://epublic-phonics.cloubot.com/",
                    go: [""],
                    bg: "https://rosaceaee.github.io/static/media/pn1.e00496c64cf59b356fd6.png",
                },
                {
                    desc: [
                        "대한적십자사",
                        "",
                        "대한적십자사 사이트 내 특정 페이지 모바일 웹 최적화 작업",
                        "css의 미디어쿼리 작업",
                        "",
                    ],
                    link: "https://culp.cloubot.com/login",
                    go: [""],
                    bg: "",
                },
                {
                    desc: [
                        "LMS",
                        "",
                        "Learning Manage System 페이지. 영어학원의 강사용, 학생용 관리자 웹,앱.",
                        "React.js, Sass기반으로 ui 퍼블리싱 80%(데스크톱, 태블릿, 모바일), 유지보수 작업",
                        "",
                    ],
                    link: "https://culp.cloubot.com/login",
                    go: [""],
                    bg: "",
                },
                {
                    desc: [
                        "크레오 영어학원 교육용 앱",
                        "",
                        "리액트 네이티브 기반으로 모든 페이지 퍼블리싱 100% 진행",
                        "Sass, React, React-native로 작업(웹앱, 안드로이드 앱 작업)",
                        "https://rosaceaee.github.io/static/media/creo.93394473494f6ef607ce.png",
                    ],
                    link: "https://play.google.com/store/apps/details?id=com.culpmobile.creo",
                    go: [""],
                    bg: "https://rosaceaee.github.io/static/media/creo.93394473494f6ef607ce.png",
                },
                {
                    desc: [
                        "파란관세사무소",
                        "",
                        "퍼블리싱 100%(데스크톱, 태블릿, 모바일)",
                        "자잘한 오류가 상당히 많아 유지보수 작업. 포털 사이트 리뉴얼과 고객사 전용 빌더 레이아웃, 기능(서버 디비에서 페이지로 ajax를 이용해 불러오는 등) 작업을 수행.            ",
                        "https://corydalis.github.io/pt/img/blue1.png",
                    ],
                    link: "http://bluecustoms.co.kr/",
                    go: [""],
                    bg: "https://corydalis.github.io/pt/img/blue1.png",
                },
                {
                    desc: [
                        "스펙토리",
                        "",
                        "메인 플랫폼 사이트의 유지보수 작업",
                        " jQuery로 유지보수",
                        "https://corydalis.github.io/pt/img/blue1.png",
                    ],
                    link: "https://www.spectory.net/",
                    go: [""],
                    bg: "https://corydalis.github.io/pt/img/spec1.png",
                },
                {
                    desc: [
                        "서울여대 아동학과",
                        "",
                        "추가 요청으로 메인페이지, 학과소개 페이지 유지보수 참여",
                        "jQuery로 유지보수",
                        "https://corydalis.github.io/pt/img/blue1.png",
                    ],
                    link: "https://childstudy.swu.ac.kr/",
                    go: [""],
                    bg: "https://corydalis.github.io/pt/img/sw1.png",
                },
                {
                    desc: [
                        "해양수산창업콘테스트",
                        "",
                        "유지보수 참여",
                        "jQuery로 유지보수",
                        "",
                    ],
                    link: "http://www.seastartup.kr/home/start.php",
                    go: [""],
                    bg: "https://rosaceaee.github.io/static/media/sea.1d75ab5657470f136abb.png",
                },
                {
                    desc: [
                        "SSmedipia",
                        "",
                        "디자인: 메인페이지, 서브페이지 레이아웃 참여, 퍼블리싱 및 유지보수 참여 100%",
                        "jQuery로 유지보수",
                        "https://corydalis.github.io/pt/img/ss1.png",
                    ],
                    link: "http://www.ssmedipia.com/",
                    go: ["ddddd"],
                    bg: "https://corydalis.github.io/pt/img/ss1.png",
                },
                {
                    desc: [
                        "공간산업 주식회사",
                        "",
                        "디자인: 메인페이지, 서브페이지 레이아웃 참여, 퍼블리싱 및 유지보수 참여 100%",
                    ],
                    link: "http://www.spcdoor.com/",
                    go: [""],
                    bg: "https://corydalis.github.io/pt/img/sp1.png",
                },
            ],
        },
        en: {
            langs: [
                {
                    desc: [
                        "Vocabulary note(private)",
                        "",
                        "Personal Toy Project, expected main target is middle-aged studying basic English words and still developing add-ons, only on mobile screen.(Only for korean)",
                        "with React, SASS",
                        "",
                    ],
                    link: "https://rosaceaee.github.io/studyLang_en/",
                    bg: "",
                },
                {
                    desc: [
                        "Meta exam",
                        "",
                        "Designed few pages, developed all the UI pages(including responsive work), maintenance of UI structure",
                        "Site for English exam in English school teachers built only React.js.",
                        "https://rosaceaee.github.io/static/media/meta3.904951598c3fff97aade.jpg",
                    ],
                    link: "https://metaexam-lexile.com/meta-login",
                    bg: "https://rosaceaee.github.io/static/media/meta3.904951598c3fff97aade.jpg",
                },
                {
                    desc: [
                        "Phonics monster",
                        "",
                        "maintenance of UI structure, responsive design",
                        "Web and Mobile App for English learning. Participated in maintanance of UI(responsive)",
                        "https://rosaceaee.github.io/static/media/pn1.e00496c64cf59b356fd6.png",
                    ],
                    link: "https://epublic-phonics.cloubot.com/",
                    go: [""],
                    bg: "https://rosaceaee.github.io/static/media/pn1.e00496c64cf59b356fd6.png",
                },
                {
                    desc: [
                        "LMS",
                        "",
                        "App for learning English Creo English school(Learning Manage System page).",
                        "Developed React-Native.js, maintained the UI to all the pages",
                    ],
                    link: "https://culp.cloubot.com/login",
                    go: [""],
                    bg: "https://rosaceaee.github.io/static/media/creo.93394473494f6ef607ce.png",
                },
                {
                    desc: [
                        "English learning app for Creo english school",
                        "",
                        "English learning tool for Creo english school",
                        "Developed the UI to all the pages with Sass, React, React-Native. (Web app and Android app)",
                        "https://rosaceaee.github.io/static/media/creo.93394473494f6ef607ce.png",
                    ],
                    link: "https://play.google.com/store/apps/details?id=com.culpmobile.creo",
                    go: [""],
                    bg: "https://rosaceaee.github.io/static/media/creo.93394473494f6ef607ce.png",
                },
                {
                    desc: [
                        "Paran customs office",
                        "",
                        "customs office in korea. Participated in responsive and layout design(desktop, tablet, mobile)",
                        "Developed using JQuery, Css3, Bootstrap",
                        "https://corydalis.github.io/pt/img/blue1.png",
                    ],
                    link: "http://bluecustoms.co.kr/",
                    go: [""],
                    bg: "https://corydalis.github.io/pt/img/blue1.png",
                },
                {
                    desc: [
                        "Spectory",
                        "",
                        "Platform site for compParticipated in layout design, and UI structure(desktop, tablet, mobile)",
                        "Developed using Jsp, jQuery",
                        "",
                    ],
                    link: "https://www.spectory.net/",
                    go: [""],
                    bg: "https://corydalis.github.io/pt/img/spec1.png",
                },
                {
                    desc: [
                        "Childstudy Dept. of Seoul women's university ",
                        "",
                        "Participated in UI maintenance of main page, some of detail pages",
                        "Developed using JQuery, Css3, Bootstrap",
                        "https://corydalis.github.io/pt/img/blue1.png",
                    ],
                    link: "https://childstudy.swu.ac.kr/",
                    go: [""],
                    bg: "https://corydalis.github.io/pt/img/sw1.png",
                },
                {
                    desc: [
                        "Contest of startup in Ministry of Oceans and Fisheries",
                        "",
                        "Site for national contest. Participated in UI maintenance",
                        "Developed using JQuery, Css3",
                        "https://corydalis.github.io/pt/img/blue1.png",
                    ],
                    link: "http://www.seastartup.kr/home/start.php",
                    go: [""],
                    bg: "https://rosaceaee.github.io/static/media/sea.1d75ab5657470f136abb.png",
                },
                {
                    desc: [
                        "SSmedipia",
                        "",
                        "The company about blood clotting diagnostic equipment. Participated in responsive and layout design, UI structure(desktop, tablet, mobile)",
                        "Developed using JQuery, Css3, Bootstrap",
                        "https://corydalis.github.io/pt/img/ss1.png",
                    ],
                    link: "http://www.ssmedipia.com/",
                    go: [""],
                    bg: "https://corydalis.github.io/pt/img/ss1.png",
                },
                {
                    desc: [
                        "Gonggan instructure Inc.",
                        "",
                        "The company to supply doors for various industry. Participated in layout design, and UI structure(desktop, tablet, mobile)",
                        "Developed using JQuery, Css3, Bootstrap",
                    ],
                    link: "http://www.spcdoor.com/",
                    go: [""],
                    bg: "https://corydalis.github.io/pt/img/sp1.png",
                },
            ],
        },
        ja: {
            langs: [
                {
                    desc: [
                        "簡単な英語単語ツール",
                        "",
                        "個人プロジェクト。使用対象は基礎的な英語単語の勉強をしているお年寄りさんで、他の技能も追加予定。スマートフォンのみ使用可能(韓国語のみ提供してます)",
                        "React, SASSで設計・実装",
                        "",
                    ],
                    link: "https://rosaceaee.github.io/studyLang_en/",
                    bg: "",
                },
                {
                    desc: [
                        "Meta exam",
                        "",
                        "(内部方針で外部からアクセスが不可ですのでご了承ください) 英語塾で行う英語試験ページ。PCとタブレットPCのスクリーンに最適化。全体ページのUI実装、メンテナンス,テスト",
                        "REACT・SASSでUI開発",
                        "https://rosaceaee.github.io/static/media/meta3.904951598c3fff97aade.jpg",
                    ],
                    link: "https://metaexam-lexile.com/meta-login",
                    bg: "https://rosaceaee.github.io/static/media/meta3.904951598c3fff97aade.jpg",
                },
                {
                    desc: [
                        "Phonics monster",
                        "",
                        "(内部方針で外部からアクセスが不可ですのでご了承ください) 英語発音教育のアプリ。UIメンテナンス",
                        "REACT・SASSでUI作業。主に全てのページのレスポンシブ実装・一部メンテナンス",
                        "https://rosaceaee.github.io/static/media/pn1.e00496c64cf59b356fd6.png",
                    ],
                    link: "https://epublic-phonics.cloubot.com/",
                    go: [""],
                    bg: "https://rosaceaee.github.io/static/media/pn1.e00496c64cf59b356fd6.png",
                },
                {
                    desc: [
                        "LMS",
                        "",
                        "(内部方針で外部からアクセスが不可ですのでご了承ください) 英語塾の教師・学生向け管理者ページ(Learning manage system)",
                        "React・SASSでUI開発及びメンテナンス(UIライブラリーとしてAntd(antDesign)使用)",
                        "https://rosaceaee.github.io/static/media/1.6ab6e2c6b7b236116320.png",
                    ],
                    link: "https://culp.cloubot.com/login",
                    go: [""],
                    bg: "https://rosaceaee.github.io/static/media/1.6ab6e2c6b7b236116320.png",
                },
                {
                    desc: [
                        "English learning app for Creo english",
                        "",
                        "Creo英語塾の学生向け英語教育用アプリ。Webサイトも含め全てのページのUIメンテナンス",
                        "React・CSS・SASS使用、React-NativeはUIメンテナンスのみ",
                        "https://rosaceaee.github.io/static/media/creo.93394473494f6ef607ce.png",
                    ],
                    link: "https://play.google.com/store/apps/details?id=com.culpmobile.creo",
                    go: [""],
                    bg: "https://rosaceaee.github.io/static/media/creo.93394473494f6ef607ce.png",
                },
                {
                    desc: [
                        "パラン関税事務所",
                        "",
                        "関税事務所のサイト。パランは韓国語で「青」の意味で、カラーも同じく青色で選択。メインカラーデザイン・レイアウトデザイン及びUI実装。",
                        "CSS・Bootstrap・JQueryで開発",
                        "https://corydalis.github.io/pt/img/blue1.png",
                    ],
                    link: "http://bluecustoms.co.kr/",
                    go: [""],
                    bg: "https://corydalis.github.io/pt/img/blue1.png",
                },
                {
                    desc: [
                        "スペックトリ",
                        "",
                        "韓国国内の公募展をまとめたサイト。提供してるホームページビルダーのサービスもメンテナンスも担当。UIメンテナンス、レスポンシブのリニューアル",
                        "CSS・JQueryで開発",
                        "https://corydalis.github.io/pt/img/blue1.png",
                    ],
                    link: "https://www.spectory.net/",
                    go: [""],
                    bg: "https://corydalis.github.io/pt/img/spec1.png",
                },
                {
                    desc: [
                        "ソウル女子大学校 児童学科",
                        "",
                        "主にメンテナンス担当。メイン、学科紹介ページのUIメンテナンス作業",
                        "CSS・Bootstrap・JQueryでメンテナンス",
                        "https://corydalis.github.io/pt/img/blue1.png",
                    ],
                    link: "https://childstudy.swu.ac.kr/",
                    go: [""],
                    bg: "https://corydalis.github.io/pt/img/sw1.png",
                },
                {
                    desc: [
                        "韓国海洋水産部の公募展サイト",
                        "",
                        "サイトのリニューアル・UIメンテナンス作業",
                        "CSS・JQueryで一部実装及びメンテナンス",
                        "https://corydalis.github.io/pt/img/blue1.png",
                    ],
                    link: "http://www.seastartup.kr/home/start.php",
                    go: [""],
                    bg: "https://rosaceaee.github.io/static/media/sea.1d75ab5657470f136abb.png",
                },
                {
                    desc: [
                        "SSmedipia",
                        "",
                        "血液に関する韓国国内企業で、レスポンシブ・レイアウトデザイン及びUIメンテナンス",
                        "CSS・Bootstrap・JQueryで開発",
                        "https://corydalis.github.io/pt/img/ss1.png",
                    ],
                    link: "http://www.ssmedipia.com/",
                    go: [""],
                    bg: "https://corydalis.github.io/pt/img/ss1.png",
                },
                {
                    desc: [
                        "コンガン産業株式会社",
                        "",
                        "産業用ドア制作企業、レイアウトデザイン及びUIメンテナンス",
                        "CSS・Bootstrap・JQueryで開発",
                    ],
                    link: "http://www.spcdoor.com/",
                    go: [""],
                    bg: "https://corydalis.github.io/pt/img/sp1.png",
                },
            ],
        },
    },
    ABOUT: {
        ko: {
            langs: [
                {
                    key: 1,
                    desc: [
                        "장영주",
                        "웹 퍼블리셔",
                        "원만한",
                        "끈기있는",
                        "차분한",
                        "고여있는 것보다 접해보지 못한 다양한 경험을 하는 것을 좋아합니다. ",
                        "IT업계에서 근무하는 동안 UI디자인과 프론트엔드 개발에 관심이 많아 디자인과 개발 사이에서 유연하게 대응할 수 있습니다.",
                        "쉬는 날에는 주로 닌텐도 스위치게임을, 조깅 혹은 자전거 라이딩을, 친구들과 산책을 하며 재충전의 시간을 가지고 있습니다! 물론 mdn 문서를 보며 개발공부도 꾸준히 하고있습니다. ",
                    ],
                },
            ],
        },
        en: {
            langs: [
                {
                    key: 2,
                    desc: [
                        "young joo Jang",
                        "UI developer",
                        "flexible",
                        "patient",
                        "calm",
                        "Likes having various experience that haven't experienced before using new ways.",
                        "I'm interested in UI design, frontend development, and can handle flexibly between it.",
                        "And in out of the computer, I usually play a nintendo switch games(Zelda series), jogging and riding bycircle, hangout with my friends. Of course, Studying a development and design also!",
                    ],
                },
            ],
        },
        ja: {
            langs: [
                {
                    key: 3,
                    desc: [
                        "young joo Jang",
                        "フロントエンドエンジニア・コーダー",
                        "柔軟な",
                        "粘り強さ",
                        "自主的",
                        "接したことがなかった多様な経験をすることが好きです。",
                        "UIデザインとフロントエンド開発に興味深くて、今までマークアップ開発とフロントエンド開発の間で働いた経験を基づいて両方対応することができます。",
                        "休みにはNintendo Switchゲームをプレイしたり、ジョギングや自転車でらいでぃんぐをしたり、友達とお出かけをして楽しく休みます！もちろん、開発とデザインの勉強も！",
                    ],
                },
            ],
        },
    },
};
exports.default = AHH;
